import { readFileSync, writeFileSync } from 'node:fs';
import { projects as baseProjects } from '../src/content.js';
import { caseStudies } from '../src/case-studies.js';
import { education, experience, skills } from '../src/profile.js';
import { icon } from '../src/icons.js';
const projects = baseProjects.map(p => ({ ...p, ...caseStudies[p.slug] }));
const pages = [{slug:'index',nav:'Home',title:'Le Huy Hung'}, {slug:'about',nav:'About Me',title:'About Me'}, ...projects];
const esc = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function dimensions(path) {
 const b=readFileSync(path);
 if(path.endsWith('.png')) return [b.readUInt32BE(16),b.readUInt32BE(20)];
 let i=2; while(i<b.length){ if(b[i]!==255){i++;continue;} const m=b[i+1]; if([192,193,194,195,197,198,199,201,202,203,205,206,207].includes(m))return [b.readUInt16BE(i+7),b.readUInt16BE(i+5)]; i+=2+b.readUInt16BE(i+2); } return [1200,900];
}
function figure(folder,file,caption,cls='technical',eager=false){
 const path=`asset/${folder}/${file}`;const [w,h]=dimensions(path);
 return `<figure class="image-frame ${cls} ${h>w*1.2?'portrait':''}"><button class="image-button" data-enlarge aria-label="Enlarge: ${esc(caption)}"><img src="./${path}" width="${w}" height="${h}" alt="${esc(caption)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async"><span class="enlarge-hint" aria-hidden="true">↗</span></button><figcaption>${esc(caption)}</figcaption></figure>`;
}
function home(){return `<section class="home-layout"><div class="home-copy"><p class="eyebrow entrance">MECHATRONICS / ROBOTICS / INTEGRATION</p><h1 class="entrance">Le Huy Hung<span class="red">.</span></h1><p class="profession entrance">Mechatronics &amp;<br>Robotics Engineer</p><p class="summary entrance">A BK-er who loves robotics and building things that work. I connect mechanical design, embedded electronics, and software to turn ideas into working robotic systems.</p><div class="home-actions entrance"><a class="button primary" href="./asset/file/CV_LeHuyHung.pdf" download="Le-Huy-Hung-CV.pdf">${icon('download')} Download CV</a><a class="button secondary" href="./about.html">Explore ${icon('arrow')}</a></div><address class="contacts entrance"><a href="tel:+84375255155">${icon('phone')}<span>+84 375 255 155</span></a><span>${icon('location')}<span>Ho Chi Minh City, Vietnam</span></span><a href="mailto:huyhuzg@gmail.com">${icon('email')}<span>huyhuzg@gmail.com</span></a><div class="socials"><a aria-label="Le Huy Hung on GitHub" href="https://github.com/HryHung" target="_blank" rel="noopener noreferrer">${icon('github')} GitHub</a><a aria-label="Le Huy Hung on LinkedIn" href="https://www.linkedin.com/in/hung-le-huy-09823627b/" target="_blank" rel="noopener noreferrer">${icon('linkedin')} LinkedIn</a></div></address></div>${figure('general','wallpaper.png','A personal collection of engineering projects.','home-wallpaper entrance',true)}</section>`;}
function about(){return `<header class="page-heading entrance"><p class="eyebrow">02 / ABOUT ME</p><h1>Engineering across disciplines<span class="red">.</span></h1><p class="lead">My mechatronics background at HCMUT connects mechanical design, embedded electronics, and software integration. I’m interested in how these disciplines come together in robotics—from CAD and control models to prototype testing and system-level debugging.</p></header><section class="about-section reveal"><div><p class="eyebrow">FOUNDATION</p><h2>Education</h2></div><article class="org education"><img src="./asset/general/bachkhoa.png" width="80" height="80" alt="HCMUT university logo"><div><span class="date">${education.dates}</span><h3>${education.name}</h3><p class="position">${education.degree}</p><p>${education.details[0]}</p><p>${education.details[1]}</p><span class="credential">TOEIC 820</span></div></article></section><section class="about-section reveal"><div><p class="eyebrow">INDUSTRY &amp; COMMUNITY</p><h2>Experience</h2></div><div class="experience-list">${experience.map(e=>`<article class="org"><img src="./asset/general/${e.logo}" width="80" height="80" loading="lazy" alt="${esc(e.name)} logo"><div><span class="date">${e.dates}</span><h3>${e.name}</h3><p class="position">${e.position}</p><ul>${e.bullets.map(b=>`<li>${b}</li>`).join('')}</ul></div></article>`).join('')}</div></section><section class="skills-section reveal"><div class="section-heading"><p class="eyebrow">PRACTICAL TOOLKIT</p><h2>Skills</h2></div><div class="skill-grid">${skills.map(([ic,name,list])=>`<article>${icon(ic)}<h3>${name}</h3><p>${list}</p></article>`).join('')}</div></section>`;}
function processDiagram(p){return p.flow?`<div class="process-diagram reveal"><p class="eyebrow">${p.slug==='hand-gesture'?'RECOGNITION PIPELINE':'SYSTEM WORKFLOW'}</p><ol>${p.flow.map((step,i)=>`<li><span class="step-number">0${i+1}</span>${esc(step)}</li>`).join('')}</ol></div>`:'';}
function project(p,i){return `<section class="project-opening"><header class="project-heading entrance"><p class="eyebrow">${String(i+1).padStart(2,'0')} / ENGINEERING CASE STUDY</p><h1>${p.title}<span class="red">.</span></h1><p class="subtitle">${p.subtitle}</p></header><div class="project-hero"><div class="hero-content"><h2 class="eyebrow entrance">OVERVIEW</h2><p class="abstract entrance">${p.abstract}</p><dl class="specs entrance">${p.specs.map(([v,k])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl><p class="highlight entrance"><span aria-hidden="true">↗</span>${p.highlight}</p></div>${figure(p.folder,p.main,p.mainCaption,'hero-image entrance',true)}</div><div class="tools entrance"><h2>Main Tools</h2><ul>${p.tools.split(' · ').map((t,j)=>`<li style="--i:${j}">${t}</li>`).join('')}</ul></div></section><section class="engineering"><div class="section-heading reveal"><p class="eyebrow">DESIGN / BUILD / EVALUATE</p><h2>Engineering Approach</h2><p>${p.overview}</p></div>${processDiagram(p)}${p.sections.map((s,j)=>`<article class="case-section reveal ${s.images.length?'':'text-only'}"><div class="case-copy"><span class="section-index">${String(j+1).padStart(2,'0')}</span><h3>${s.title}</h3>${s.paragraphs.map(t=>`<p>${esc(t)}</p>`).join('')}</div>${s.images.length?`<div class="support-images ${s.images.length>1?'paired':''}">${s.images.map(([f,c,type])=>figure(p.folder,f,c,type)).join('')}</div>`:''}</article>`).join('')}</section><section class="results reveal"><div class="section-heading"><p class="eyebrow">EVIDENCE &amp; OUTCOMES</p><h2>Results &amp; Achievements</h2></div><ul class="result-list">${p.results.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><aside class="limitations"><h3>Evidence limits</h3><p>${esc(p.note)}</p></aside>${p.plot?figure(p.folder,...p.plot,'results-gallery'):''}<p class="source-note">Source basis: ${esc(p.source)}</p></section>`;}
for(const [i,p] of pages.entries()) {
 const prev=pages[(i+8)%9],next=pages[(i+1)%9];
 const desc=p.abstract||(i===0?'Le Huy Hung — Mechatronics & Robotics Engineer. Mechanical design, embedded electronics, and software for working robotic systems.':'Education, industry experience, and engineering skills of Le Huy Hung.');
 const navLink=(q,j)=>`<a href="./${q.slug}.html" ${j===i?'aria-current="page"':''}>${j===0?icon('home'):''}${q.nav}</a>`;
 const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="${esc(desc)}"><meta name="theme-color" content="#FFFFFF"><title>${i===0?'Le Huy Hung — Mechatronics & Robotics Engineer':`${p.title} — Le Huy Hung`}</title><link rel="icon" type="image/svg+xml" href="./favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="./src/style.css"><script type="module" src="./src/main.js"></script></head><body class="page-${p.slug}"><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><nav aria-label="Main navigation">${navLink(pages[0],0)}<button class="menu-toggle" aria-expanded="false" aria-controls="nav-links">Menu <span aria-hidden="true">☰</span></button><div id="nav-links">${pages.slice(1).map((q,j)=>navLink(q,j+1)).join('')}</div></nav></header><main id="main">${i===0?home():i===1?about():project(p,i)}</main><footer class="page-footer"><a class="button footer-button" rel="prev" href="./${prev.slug}.html"><span aria-hidden="true">←</span><span><small>Previous page</small>${prev.nav}</span></a><div class="page-count"><span>${String(i+1).padStart(2,'0')}</span> / 09</div><a class="button footer-button" rel="next" href="./${next.slug}.html"><span><small>Next page</small>${next.nav}</span><span aria-hidden="true">→</span></a></footer><dialog class="viewer" aria-label="Enlarged project image"><button class="viewer-close" autofocus aria-label="Close image viewer">Close ×</button><figure><img alt=""><figcaption></figcaption></figure></dialog></body></html>`;
 writeFileSync(`${p.slug}.html`,html);
}
console.log('Generated 9 source-reviewed portfolio pages.');
