// Source-reviewed narratives. Keep design targets, simulations and physical tests distinct.
export const caseStudies = {
  amr: {
    subtitle: 'Indoor Warehouse Transportation', highlight: 'Physical mapping, waypoint missions & web monitoring demonstrated',
    abstract: 'An indoor transportation robot connecting warehouse tasks with mapping, navigation, and visual docking. Mechanical design, electrical architecture, embedded motor control, and ROS 2 come together in a working prototype operated through a browser interface.',
    overview: 'The work covers a full-scale engineering design and a lower-power physical prototype. The prototype validates control integration and operating principles; it does not validate every payload, speed, or endurance requirement of the full design.',
    flow: ['Web mission', 'ROS 2 / Nav2', 'ESP32 control', 'Differential drive'],
    sections: [
      { title: 'Requirements, drivetrain & structural design', paragraphs: ['Payload, footprint, speed, operating time, and docking requirements set the design envelope. Weighted Pugh matrices compared drivetrain, sensing, power, and controller options before detailed component selection.', 'A differential-drive arrangement with centrally positioned drive wheels was selected. The mechanical work connected torque and transmission calculations to shaft dimensions, bearing selection, load stability, and braking conditions. CAD mass-property analysis informed packaging; finite-element analysis assessed critical drivetrain components. These calculations and simulations support the design, rather than proving full-load prototype capability.'], images: [['mass_est.jpg','CAD packaging and mass-distribution estimate.','technical'],['flange.jpg','Finite-element analysis of the drivetrain flange.','technical']] },
      { title: 'Power distribution & embedded motion control', paragraphs: ['The electrical architecture separates propulsion and control power distribution, with battery, motor-driver, sensor, and charging arrangements considered together. This makes the power system part of the overall robot design rather than an isolated electronics task.', 'Raspberry Pi handles higher-level processing, while ESP32 acquires encoder data and executes wheel-speed control. Differential-drive kinematics translate robot motion commands into wheel commands, with PI/PID feedback at the embedded layer. The physical build tests communication and actuation across these layers.'], images: [['elec.png','Prototype hardware connecting Raspberry Pi, ESP32, and actuation.','photo']] },
      { title: 'Mapping, waypoint navigation & visual docking', paragraphs: ['SLAM Toolbox builds the map while an operator manually drives the robot, with a forward-obstacle check. AMCL then localizes the robot on a saved map, and Nav2 executes a configured waypoint sequence. The Flask interface brings manual control, map creation, mission configuration, and execution status into one operating workflow.', 'For final approach, the camera was calibrated using 50 checkerboard images. AprilTag observations support approach correction and expose distance and alignment feedback in the interface. The docking stage is distinct from Nav2 waypoint arrival: the documented navigation-only test did not establish precise final docking.'], images: [['docking3.png','Flask interface with map, mission controls, and AprilTag feedback.','interface']] },
      { title: 'What the prototype tests establish', paragraphs: ['Physical mapping and waypoint missions demonstrated that the operator interface, ROS 2 software, and embedded control could work together. Map dimensions were compared with rounded reference measurements obtained using an iPhone measuring application; that method also contributes uncertainty.', 'The path analysis compares onboard localization with the Nav2 reference path over 297 moving samples. It measures agreement within the robot’s own navigation system, not independently surveyed positioning accuracy. Wheel-speed feedback remained inconsistent, and continuous camera streaming sometimes overloaded the Raspberry Pi.'], images: [] }
    ],
    results: ['Physical mapping, waypoint execution, and web status updates demonstrated.', 'Room-map differences: 0.16 m in width (2.11%) and 0.10 m in length (1.04%) against the report’s reference measurements.', 'One AprilTag docking case: 0.500 m target, 0.515 m camera-reported distance — 15 mm distance error.', 'Onboard estimated path deviation: 16.5 mm mean and 159.7 mm maximum across 297 moving samples.'],
    note: 'The 20 kg payload, 1 m/s maximum speed, and ≥4-hour runtime are design targets, not fully validated prototype capabilities. The docking case does not establish repeatability or completed autonomous charging. Path deviation is not an independent ground-truth measurement.',
    source: 'Capstone report, chapters 2–6; portfolio pages 2–3; supplied project summary.'
  },
  nexcube: {
    highlight: 'BKI Top 5 · Four assembled workstation modules',
    abstract: 'A reconfigurable electronics workstation bringing battery power, testing, adjustable power, and soldering into a shared physical system. A standardized mechanical–electrical interface combines magnetic alignment, spring contacts, orientation control, and common power distribution.',
    overview: 'The concept addresses the wiring and assembly overhead of separate tools in a small electronics workspace. The technical disclosure concentrates on the reusable connection system; the product photographs and CV document four functional prototypes.',
    flow: ['Align modules', 'Guide orientation', 'Compress contacts', 'Share power'],
    sections: [
      { title: 'Four tools, one modular workstation', paragraphs: ['The Battery, Tester, Power, and Soldering modules each package a practical workstation function. The portfolio describes an 18650 battery assembly with charging and battery management, an LCR component tester, an adjustable power module, and a soldering module using a custom PCBA.', 'Rather than requiring a separate enclosure and connection scheme for every tool, the project develops a common physical format. The CV records housing, wiring-bus, and PCBA development for all four prototypes. The assembled product shows the architecture brought into physical form, while the team presentation places that work in its development context.'], images: [['4cube.jpg','Battery, Tester, Power, and Soldering modules, assembled together.','photo']] },
      { title: 'Separating alignment from electrical contact', paragraphs: ['The adapter sits between a power module and a functional module, or between successive modules. Magnets assist positioning; guide surfaces and keyed or asymmetric geometry support the intended orientation. The contact layout provides a further mechanical–electrical constraint against incorrect mating.', 'Spring contacts, such as pogo pins, compress against mating pads when the adapter reaches its working position. That contact pressure is the electrical connection mechanism; magnetic positioning is a separate function. A positive-supply and ground bus can pass power onward through successive modules without a separate supply adapter for each unit.'], images: [['pin.png','Adapter geometry and spring-contact arrangement.','technical']] },
      { title: 'Enclosure development & evidence boundaries', paragraphs: ['Printed enclosure development integrates the external connection features with the internal electronics. SolidWorks design and Bambu Lab print preparation support iteration on the module housings and adapter fit. The physical modules establish prototype assembly, not a quantified reduction in setup time or a durability rating.', 'The disclosure documents drawings, component descriptions, operating sequences, and draft claims for a potential patent or utility-solution application. Electrical protection, electronic identification, and controlled power switching are optional configurations in that document, not confirmed prototype features. No connection-cycle, contact-resistance, current-capacity, or thermal test is supplied.'], images: [['print.png','Enclosure print preparation for the modular housing.','technical']] }
    ],
    results: ['BKI — Top 5.', 'Supported by two PhD mentors, both Vice Deans, and four advisors.', 'Four assembled workstation modules with a documented mechanical–electrical connection architecture.', 'Detailed technical disclosure and adapter drawings prepared.'],
    note: 'The disclosure is a draft, not evidence of a filed or granted patent. Connection lifetime, contact resistance, thermal performance, current capacity, and setup-time savings have not been quantified in the supplied material.',
    source: 'NEXCUBE technical disclosure; portfolio page 4; CV; supplied project summary and achievement details.'
  },
  hexapod: {
    subtitle: 'Modular Walking Platform', highlight: 'Physical 18-DOF platform with kinematics and gait simulation',
    abstract: 'A six-legged robotics platform for exploring mechanical design, inverse kinematics, gait generation, and embedded control. Three actuated joints per leg create an 18-DOF structure for experimentation with mechanisms, electrical interfaces, and future sensing equipment.',
    overview: 'The project connects university robotics concepts with a physical platform. Mechanical assembly, firmware, and simulation form separate but related parts of the work; simulated motion is not presented as measured walking performance.',
    flow: ['Gait planning', 'Inverse kinematics', 'Servo control', 'Leg actuation'],
    sections: [
      { title: 'Six legs built around modular interfaces', paragraphs: ['The body and leg assemblies were modeled in SolidWorks. Each leg contains coxa, femur, and tibia joints, giving three actuated degrees of freedom for foot positioning. Modular joint and leg interfaces are intended to simplify assembly and replacement during development.', 'The architecture combines available electronics modules with custom PCB work. Power contacts and alignment pins provide the mechanical–electrical interface, while magnetic features assist positioning. The magnets are not described as current-carrying contacts.'], images: [['leg_kinematic.png','SolidWorks leg structure and the three-joint kinematic model.','technical']] },
      { title: 'From a desired foot position to joint commands', paragraphs: ['MATLAB modeling investigates the relationship between the desired foot position and joint angles. Inverse kinematics provides that transformation, allowing gait development to be expressed in terms of foot trajectories rather than independent servo settings.', 'The software architecture separates high-level commands, gait planning, inverse kinematics, servo control, and hardware drivers. The gait model provides a way to examine coordinated movement before drawing conclusions about the behavior of the assembled mechanism.'], images: [['model.png','MATLAB tripod-gait model — simulated motion.','technical']] },
      { title: 'Embedded integration & actuator feedback', paragraphs: ['Embedded C firmware on ESP32 implements low-level I²C driver integration and a servo-control layer. The central controller and electrical architecture connect the 18 actuators to the planned motion pipeline.', 'Early physical use exposed an actuator reliability issue: the project note records plastic MG996 servo gearboxes stripping after approximately four to five runs. That observation informs actuator selection and illustrates why successful simulation alone cannot establish hardware reliability. Terrain-aware walking, IMU/force feedback, advanced gait adaptation, and a possible ROS interface remain future work.'], images: [['elec.png','ESP32-based electrical and servo-driver architecture.','technical']] }
    ],
    results: ['Physical six-legged, 18-DOF robot assembled.', 'Mechanical CAD, an electrical architecture, and gait/kinematics simulation developed.', 'Modular platform established for continued robotics experimentation.', 'Early gearbox failure documented after approximately four to five runs.'],
    note: 'The supplied evidence does not establish walking speed, payload, endurance, or measured gait stability. Simulation, physical assembly, and future sensor-feedback work are kept distinct.',
    source: 'Hexapod project note; CV; portfolio page 5, qualified by the supplied evidence summary.'
  },
  'mini-agv': {
    highlight: 'Red/blue routing demonstrated · Reported 0.35–0.40 m/s operation',
    abstract: 'A compact guided vehicle that transports manually loaded goods to destinations selected by cargo color. It follows a black line on a white surface, recognizes loading and branching locations, and routes red or blue cargo through an embedded mission sequence.',
    overview: 'The project combines a fabricated chassis, custom electronics, calibrated sensing, mathematical modeling, and feedback control. The 0.5 m/s design maximum is separate from the reported 0.35–0.40 m/s operating range.',
    flow: ['Follow line', 'Wait for cargo', 'Classify color', 'Select branch'],
    sections: [
      { title: 'Integrating the chassis, drivetrain & electronics', paragraphs: ['A differential-drive layout uses two powered wheels and a passive front support. Drivetrain sizing, center-of-gravity calculations, structural deformation, and assembly tolerances were considered as parts of the same mechanical design.', 'CAD and structural simulation supported chassis development. Custom electronics connect the ESP32, sensor inputs, and motor actuation. The completed robot brings these components together in a compact physical prototype; the structural plot remains a simulation result rather than a measured payload test.'], images: [['3d.png','Mechanical layout and component packaging.','technical'],['sim.png','Chassis deformation from structural simulation.','technical']] },
      { title: 'Calibrated sensing & nested control loops', paragraphs: ['Five TCRT5000 infrared sensors read the guide line. Their analog outputs are calibrated before a weighted-average method estimates line position. A TCS34725 color sensor uses calibrated thresholds to distinguish cargo colors.', 'PWM–encoder response data were collected for motor identification. First-order models fitted in MATLAB achieved 96.19% and 96.35% agreement with the identification data. An outer PD controller converts line-tracking error into wheel-speed demands; inner PI controllers regulate the individual wheels. MATLAB/Simulink tuning produced simulated settling times of approximately 0.15 seconds and overshoots of 1.87% and 1.92%. These are model results, not measured whole-vehicle settling times.'], images: [['elec.png','PCB layout integrating control, sensing, and motor electronics.','technical']] },
      { title: 'Mission sequencing & physical evaluation', paragraphs: ['A state machine coordinates line following, waiting for cargo, color processing, and decisions at junctions. Color recognition supplies a classification; the higher-level mission logic decides which route to follow. The web interface displays feedback during testing.', 'Evaluation combined observed route execution with a physical pen trace and the system’s estimated tracking error. One check measured approximately 2.5 mm beyond the line edge. However, the report’s conclusions disagree about satisfying the ±3 mm requirement, and its center-to-edge conversion uses a 12 mm half-width despite specifying a 26 mm line elsewhere. The observed result is retained without claiming consistently proven tracking accuracy.'], images: [['app.png','Web feedback used during vehicle monitoring and test runs.','photo']] }
    ],
    results: ['Loading-stop detection, red/blue cargo recognition, and branch selection demonstrated.', 'Reported average operating speed: 0.35–0.40 m/s; endpoint stopping error: <5 mm.', 'Motor-model fits: 96.19% and 96.35% against identification data.', 'Simulated PI wheel-control response: approximately 0.15 s settling; 1.87% and 1.92% overshoot.', 'One physical pen-trace check: approximately 2.5 mm beyond the line edge.'],
    note: 'Payload and maximum speed remain design specifications. Conflicting tracking conclusions and the line-width inconsistency prevent a claim of consistently verified ±3 mm accuracy. The report also notes sensor noise, PCB corrections, and further control tuning needs.',
    source: 'Mini AGV report, sensing/control and experimental chapters; portfolio page 6; supplied project summary.'
  },
  'printed-lens': {
    subtitle: 'Film Optics Adapted for Digital Photography', highlight: 'Functioning Sony-compatible lens & customer-approved viewfinder',
    abstract: 'A customer-driven product developed during the Technix AM internship to reuse the lens and viewfinder from a sentimental film camera. A custom printed housing, manual focusing mechanism, camera interface, and hot-shoe accessory adapt those recovered components for digital photography.',
    overview: 'The objective was to preserve usable optical elements while creating a practical mechanical interface for a modern camera. The work combines reverse engineering and optical requirements with iterative CAD, printing, fitting, and image-capture tests.',
    sections: [
      { title: 'Recovering components & defining the optical fit', paragraphs: ['Development began with the customer’s requirements and the recovered camera components. Disassembly and measurement established the dimensions needed to retain the original optics and viewfinder while designing new surrounding parts.', 'The optical–mechanical task was to understand focusing and the lens-to-sensor spacing required to form an image. The new housing needed to locate the recovered elements, provide a compatible camera interface, and allow deliberate focus adjustment. The optical reference illustrates the principle; it is not a prescription or measured performance model for this particular lens.'], images: [['lens.jpg','Recovered lens and film-camera components.','photo'],['principle.jpg','Optical-principle reference; original attribution is not supplied.','technical']] },
      { title: 'Refining the focusing mechanism through printed prototypes', paragraphs: ['The mechanism began with a helical focusing approach, then was refined into a telescoping arrangement with guidance to constrain unwanted rotation. This development connected the intended focus motion with the physical fit and compactness of the assembly.', 'SolidWorks was used to design the parts, with Cura and PETG printing supporting fabrication. Fit and printing tolerances were considered through iterative fitting, along with the intended outdoor use. Prototype feedback informed revisions to optical-element retention, focusing operation, and the camera mount. The evidence describes development iterations rather than a quantified durability test.'], images: [['final3d.jpg','CAD assembly of the housing and focusing mechanism.','technical']] },
      { title: 'Camera testing & customer delivery', paragraphs: ['The finished assembly was checked on a Sony digital camera for mount compatibility, focusing, and image capture. The supplied result photograph shows a Sony ZV-E10 displaying an image, providing direct evidence that the adapted optics and printed mechanism function together.', 'A separate hot-shoe viewfinder accessory also received customer approval. The supplied internship-report summary describes a finished product satisfactory to the customer and further company investment in development and preparation for repeat production. It does not establish a production volume, sales result, or measured optical quality.'], images: [['result.jpg','Image capture demonstrated on a Sony ZV-E10.','photo']] }
    ],
    results: ['Functioning manual-focus lens completed using recovered film-camera optics.', 'Sony camera compatibility and image capture demonstrated.', 'Separate hot-shoe viewfinder accessory approved by the customer.', 'Finished product reported as satisfactory; further product development initiated by the company.'],
    note: 'No quantitative resolution, distortion, durability, sales, or production-volume results are supplied. The evidence supports a functioning customer-oriented prototype and product-development outcome.',
    source: 'Technical-practice report, chapter 3 (pages 21–27); CV; original component, CAD, and camera-test photographs.'
  },
  merc: {
    subtitle: 'Mobile Lifter and Gripper Robot', highlight: 'Top 8 — MERC 2025',
    abstract: 'An operator-controlled competition robot combining a mobile chassis, vertical lift, and dual grippers for object handling. Mechanical actuation and embedded electronics bring movement, lifting, and gripping into one physical platform.',
    overview: 'The supplied project note and photographs document the main mechanisms and competition outcome. They support an integration case study, rather than a quantified assessment of lifting capacity or handling precision.',
    flow: ['Operator input', 'Arduino / drivers', 'Drive · lift · grip'],
    sections: [
      { title: 'A mobile base with guided vertical movement', paragraphs: ['Four GA25 motors form the drivetrain. Above the base, a slider rail guides the lifting assembly while a belt-and-pulley mechanism supplies vertical actuation. The CAD assembly and side-view photograph show how the lifting column is packaged with the mobile chassis.', 'The distinction between guidance and actuation is visible in this architecture: the rail defines the travel path, while the belt transmits motion. The supplied note identifies the components but does not provide a measured lift height or cycle time.'], images: [['3d.png','CAD assembly of the mobile platform and lift.','technical'],['side.jpg','Complete lifting column, rail, and mobile chassis.','photo']] },
      { title: 'Dual gripping & operator-controlled electronics', paragraphs: ['A dual-gripper arrangement uses GJA worm-geared motors. Together with the mobile base and lift, the grippers provide the mechanisms needed for operator-controlled object handling.', 'Electrical integration combines two Arduino Mini controllers, two drivers, and two relays. A Mini-C6 six-channel controller provides operator input. The project note also lists UART communication, but does not document the detailed signal architecture or allocation of tasks between the two controllers. The portfolio therefore avoids assuming an undocumented control topology.'], images: [['elec.png','Arduino controllers, drivers, relays, and wiring on the prototype.','photo']] }
    ],
    results: ['Top 8 — MERC 2025, as recorded in the project note.', 'Drivetrain, belt-driven lift, and dual grippers integrated on one platform.', 'Physical robot completed and entered in competition.'],
    note: 'No measured lifting capacity, lift height, cycle time, positioning accuracy, or control reliability is supplied. The event photograph does not establish an award beyond the documented Top 8 placement.',
    source: 'MERC project note; portfolio page 7; physical robot and competition photographs.'
  },
  'hand-gesture': {
    subtitle: 'Real-Time Computer Vision Application', highlight: 'Static-gesture registration and matching demonstrated',
    abstract: 'A webcam application that registers a static hand gesture and compares it with live input to change an on-screen lock state. Pretrained hand-landmark detection feeds geometric feature extraction and rule-based matching, with intermediate results visible in Streamlit.',
    overview: 'The prototype explores a complete computer-vision workflow using an ordinary webcam. Its value is in connecting capture, geometric representation, reference registration, and visible feedback—not in establishing security-grade authentication.',
    flow: ['Camera', 'Landmarks', 'Features', 'Match'],
    sections: [
      { title: 'Capturing and representing the hand', paragraphs: ['OpenCV captures webcam frames and converts them to RGB for MediaPipe Hands. The pretrained detector returns 21 landmarks per hand, providing a structured geometric representation for the application’s own analysis.', 'Instead of classifying the raw image directly, the application calculates finger configuration from those landmarks. The interface can display the camera feed and landmark overlay, making it possible to inspect the representation before interpreting a match result.'], images: [['mapping.png','The 21-landmark representation used for geometric analysis.','technical']] },
      { title: 'A ten-feature descriptor and a registered reference', paragraphs: ['The descriptor contains finger count, five individual finger angles, and four inter-finger angles. The geometric angles are computed from landmark vectors; together they represent the current static hand configuration.', 'Registration stores the reference feature vector in Streamlit session state. During comparison, finger count must match exactly, while the nine angular features must fall within a relative ±50% tolerance of the saved values. The result is rule-based matching of a reproduced gesture, not a learned identity model.'], images: [['feature_value.png','Live finger-count and angular feature values.','interface']] },
      { title: 'Interface feedback & evaluation conditions', paragraphs: ['Streamlit provides camera controls, reference registration, verification, and optional overlays. Saved, unlocked, and wrong-password states make the workflow visible. Showing intermediate features also helps explain a mismatch and supports debugging.', 'The report describes approximately 20–30 FPS, including a stated 30 FPS test at 720p. Finger-count accuracy is reported at approximately 98% under good lighting with a simple background. Gesture-match accuracy is reported at approximately 90–95%, depending on how consistently the gesture is reproduced. Low light, occlusion, and hand rotation can reduce stability.', 'No test-set size, participant count, or false-accept/false-reject evaluation is provided. The implemented workflow matches static gestures; dynamic sequences and stronger authentication remain future work.'], images: [] }
    ],
    results: ['Working webcam-based gesture registration and static matching.', 'Reported 20–30 FPS, including a stated 30 FPS at 720p test.', 'Reported approximately 98% finger-count accuracy under good lighting and a simple background.', 'Reported approximately 90–95% gesture-match accuracy, dependent on reproduction consistency.', 'Intermediate features and matching states visible for explanation and debugging.'],
    note: 'Test-set size, participant count, and false-accept/false-reject rates are unspecified. These reported demonstrations are not a validated security benchmark.',
    source: 'Computer Vision hand-gesture report, sections 2.3–2.4 and chapters 3–4; supplied project summary.'
  }
};
